### ISSUE TITLE
Bug: Full screen button unable to go back to normal mode 

### ISSUE THREAD

**Issue by hauchongtang** [RAJAGOPALAN-GANGADHARAN/JS-OS#20]
I can enter fullscreen on click but I can't close fullscreen when i click the button again.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Nice catch can you fix this up ?

**Comment by hauchongtang** [comment]
> Nice catch can you fix this up ?

Sure. Not really free atm but i will try to take a look this weekend.

**Comment by ambivert-sam** [comment]
I would want to work on this issue, Can you please assign it to me?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey sure go ahead

**Comment by ambivert-sam** [comment]
I'm stuck over here what to do?
![Screenshot (140)](https://user-images.githubusercontent.com/74984661/110983127-5dab4700-838f-11eb-802e-9feebe3f4c56.png)

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Can you tell me what issue are you facing?

**Comment by aritroCoder** [comment]
I have fixed the issue and opened a PR
