### ISSUE TITLE
Bug: Date is not correct in the taskbar section

### ISSUE THREAD

**Issue by arbazalam01** [RAJAGOPALAN-GANGADHARAN/JS-OS#23]
getMonth start from 0 to 11 for the 12 months. I think adding 1 will show the correct output.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Thanks for hunting this, will review the PR and get back to you.

**Comment by aritroCoder** [comment]
Is this closed or I can work on this?

**Comment by aritroCoder** [comment]
I have fixed the issue should I raise a PR?

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@aritroCoder sorry the OP has already completed this #24
