### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [RAJAGOPALAN-GANGADHARAN/JS-OS#26]
Add more jazz and decoration to the Readme.md; more details about the project, coding guidelines etc would be appreciated.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Can use any standard readme template; giving a colorful splash, adding badges and other dynamic meta data is highly appreciated!

**Comment by anushka-2001** [comment]
Hey Rajagopalan, I would love to contribute to this repo, I have basic knowledge of MD I guess I can pull this off

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Hey yes waiting for the PR!
