### ISSUE TITLE
Minify the deployed package

### ISSUE THREAD

**Issue by RAJAGOPALAN-GANGADHARAN** [RAJAGOPALAN-GANGADHARAN/JS-OS#27]
As of now JSOS downloads lot of unused packages which increases load on network, Hunt for unused packages and get ridf of it, by experimenting thoroughly.

**Comment by ArchismanKarmakar** [comment]
assign this to me

i have listed all of them::

Unused dependencies
* @babel/runtime
* @fortawesome/fontawesome-svg-core
* @fortawesome/free-solid-svg-icons
* @fortawesome/react-fontawesome
* @monaco-editor/react
* @react-pdf/renderer
* argparse
* glot-api
* html-to-react
* i
* jquery
* monaco-editor
* npm
* pdf-viewer-reactjs
* react-ace
* react-calendar
* react-fontawesome
* react-froala-wysiwyg
* react-items-carousel
* react-pdf
* react-read-pdf
* react-responsive-carousel
* react-router
* react-scripts
* react-slideshow-image
* react-spreadsheet
* react-trumbowyg
* react-viewer
Unused dev dependencies
* gh-pages
* react-app-rewired
Missing dependencies
* regenerator-runtime: .\src\index.js
* ace: .\src\defaultapps\texteditor\src\ext-emmet.js
* @tinymce/tinymce-react: .\src\defaultapps\markdown\markdown_editor.js
* prop-types: .\src\defaultapps\blogfeed\components\CodeBlock.js

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ArchismanKarmakar Thank you for working on this. Make sure the dev build and prod build works.

**Comment by ArchismanKarmakar** [comment]
done i have updated package.json now creating PR

**Comment by ArchismanKarmakar** [comment]
#45 

> @ArchismanKarmakar Thank you for working on this. Make sure the dev build and prod build works.
