### ISSUE TITLE
Add Cross WOC Banner or Poster

### ISSUE THREAD

**Issue by Ayush7614** [RAJAGOPALAN-GANGADHARAN/JS-OS#36]
## Is your feature request related to a problem? Please describe.
Add Cross WOC Banner or Poster

## Describe the solution you'd like
Add Cross WOC to  Banner or Poster

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Sorry, I plan on keeping this repository even after cross WOC. Hence I don't think its a very useful idea.
