### ISSUE TITLE
Add Issue and PR Templates

### ISSUE THREAD

**Issue by muthuannamalai12** [RAJAGOPALAN-GANGADHARAN/JS-OS#38]
Would like to add issue and pr templates to these project that will basically explain the type of issue and its description and also the type of pr the set of checklist that it obeys and its description

Kindly assign this to me as a part of Cross-Woc. I would love to do it

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Someone is already doing that. Thanks!
