### ISSUE TITLE
Unresponsive Clock 

### ISSUE THREAD

**Issue by ShivaRapolu01** [RAJAGOPALAN-GANGADHARAN/JS-OS#43]
The clock  which appears when time is clicked in the taskbar is not responsive. 
![taskbar_clock](https://user-images.githubusercontent.com/79957651/144212467-a1203080-f767-42bc-8ffe-415ca0fabaec.jpg)

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ShivaRapolu01 , I'm unable to reproduce this issue if I have to take a guess when screen is small this happens. Can you check if that is true. Thanks!

**Comment by ShivaRapolu01** [comment]
When the clock container is small then this is happening

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ShivaRapolu01 Right that makes sense, could you try fixing this by enforcing minimum size of container for this window!

**Comment by ShivaRapolu01** [comment]
Yeah sure

**Comment by ShivaRapolu01** [comment]
I guess this comes under easy category and some points for pointing out the issue right?
